platform:ios, '8.0'
use_frameworks!
   target 'PodDeom' do
   pod 'IQKeyboardManager', '~> 5.0.7'
   pod 'Reveal-SDK', '6'
   pod 'YYText', '~> 1.0.7'
   pod 'AFNetwork', '~> 0.1.0'
   pod 'SDWebImage'
   pod 'Tangram'
   pod 'LazyScroll'
   pod 'pop'
   pod 'FLAnimatedImage', '~> 1.0.12'

end
